name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        elixir-version: ['1.10.3', '1.11.2']
        otp-version: ['22.3', '23.0', '23.1']
        python: ['2.7', '3.6', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}
    - name: Install prerequisites
      run: |
        sudo apt install -y libzmq3-dev libsqlite3-dev
    - name: Install python packages
      run: |
        pip install pip --upgrade
        pip install tornado==4.5.3
        pip install jupyter nose
        git clone -b ielixir https://github.com/pprzetacznik/jupyter_kernel_test.git
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install elixir dependencies
      run: |
        mix deps.get
        mix deps.compile
        MIX_ENV=dev ./install_script.sh
    - name: Run tests
      run: |
        mix test
        pushd jupyter_kernel_test
        MIX_ENV=dev python test_ipython.py
        popd
    - name: Generate documentation
      run: |
        MIX_ENV=docs mix deps.get
        MIX_ENV=docs mix docs
        MIX_ENV=docs mix inch.report

